server:
  port: 8082

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=customer_db;encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

jwt:
  secret: ijBppcckvyt9FifTWWA4Uh0LQNydMK7cMbW8HaLtbLnVu1bd4wk35ZVRNGpzmJxR
  expiration: 86400000